// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from 'dotenv';
import { defineConfig } from 'prisma/config';

// Load environment-specific .env file
const envFile = `.env.${process.env['NODE_ENV'] || 'development'}`;
dotenv.config({ path: envFile });

// Validate DATABASE_URL exists
const databaseUrl = process.env['DATABASE_URL'];
if (!databaseUrl) {
  throw new Error(`DATABASE_URL is not defined in ${envFile}`);
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: databaseUrl,
  },
});
